# *************************** SETS ***********************
# SE USAN PARA EVITAR DUPLICADOS PORQUE TIENE UN ACCESO MUY APIDO. EL AL LISTA ES MAS LENTO
my_set = {"Ana", "Pedro"}
print(my_set)

# INSERTAR ELEMENTO
my_set.add("Ribera")
print(my_set)
# set[0] NO FUNCIONA

# ELIMINAR ELEMENTO
my_set.remove("Ana")
print(my_set)

# ACTUALIZAR: UPDATE AMPLIA LOS DATOS QUE HAY EN EL SET (cancatena)
# PARA CAMBIAR UN DATO POR OTRO ES NECESARIO BORRARLO Y CREARLO DE NUEVO

# ORDENAR: POR DEFINICION, UN SET NO PUEDE SER ORDENADO